
title: Spitfyre Security & Development Blog
email: spitfire94155@gmail.com
description: Information Security and Android Development Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spitfy.re" # the base hostname & protocol for your site, e.g. https://example.com
github_repo: https://www.github.com/spitfire55.github.io# the GitHub repo name for your project
github_username: spitfire55
google_analytics: UA-85436923-1

twitter_username: spitfire55_
github_username: spitfire55
instagram_username: spitfire55

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: blue
highlighter: rouge

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exclude: ['.sass_cache', 'README.md']
sass:
    sass_dir: '_assets/_sass'
permalink: '/:title/'

# Defaults
defaults:
    -
        scope:
            path: "_pages"
        values:
            is_in_nav: true
