# Site settings

title: Spitfire Tech
email: spitfire94155@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Infosec and Android Dev Blog
baseurl: ""
url: "http://spit-fire.tech" # the base hostname & protocol for your site
timezone: America/New_York

#Social settings
RSS: false
twitter_username: spitfire55_
github_username:  spitfire55
facebook_username: dale.f.lakes
linkedin_username: dale-lakes-a548a1119

#Build settings

exclude: ["README.md", "about.md"]


# Markdown settings
markdown: kramdown
theme: minima
